# Generated by Django 5.0.6 on 2024-06-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_genre_alter_movie_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='year_release',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
