# Generated by Django 5.0.6 on 2024-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_release_date_movie_year_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
