# Generated by Django 5.0.6 on 2024-06-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_public_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
